// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AddLabelsToSourceAlphaInput - Applies an existing label to an existing Source.
type AddLabelsToSourceAlphaInput struct {
	// The labels to associate with a Source.
	Labels []LabelAlpha `json:"labels"`
}
