// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AdvancedWarehouseSyncScheduleV1Input - Defines the advanced sync schedule for a Warehouse.
type AdvancedWarehouseSyncScheduleV1Input struct {
	// A list that contains the times when syncs should occur.
	Times []WarehouseAdvancedSyncV1 `json:"times"`
	// A TZ-database timezone for this sync schedule.
	Timezone string `json:"timezone"`
}

func (o *AdvancedWarehouseSyncScheduleV1Input) GetTimes() []WarehouseAdvancedSyncV1 {
	if o == nil {
		return []WarehouseAdvancedSyncV1{}
	}
	return o.Times
}

func (o *AdvancedWarehouseSyncScheduleV1Input) GetTimezone() string {
	if o == nil {
		return ""
	}
	return o.Timezone
}
