// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APICallSnapshotV1 - A snapshot of the number of API calls for a given Workspace.
type APICallSnapshotV1 struct {
	// A bigint of the number of API calls in this snapshot.
	APICalls string `json:"apiCalls"`
	// Timestamp of this snapshot within the billing cycle in the ISO-8601 format.
	Timestamp string `json:"timestamp"`
}

func (o *APICallSnapshotV1) GetAPICalls() string {
	if o == nil {
		return ""
	}
	return o.APICalls
}

func (o *APICallSnapshotV1) GetTimestamp() string {
	if o == nil {
		return ""
	}
	return o.Timestamp
}
