// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AuditEventV1 - Represents an Audit Trail event.
type AuditEventV1 struct {
	// The user or API token that triggered this event.
	Actor string `json:"actor"`
	// Unique identifier for this audit trail event.
	ID string `json:"id"`
	// The identifier of the resource affected by this event.
	ResourceID string `json:"resourceId"`
	// The name of the resource affected by this event.
	ResourceName string `json:"resourceName"`
	// The kind of resource affected by this event.
	ResourceType string `json:"resourceType"`
	// The timestamp of this event in ISO-8601 format.
	Timestamp string `json:"timestamp"`
	// The type of this event.
	Type string `json:"type"`
}
