// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BreakdownBeta - The breakdown of a metric.
type BreakdownBeta struct {
	// The name of the metric.
	MetricName string `json:"metricName"`
	// Number of occurrences of the metric.
	Value float64 `json:"value"`
}

func (o *BreakdownBeta) GetMetricName() string {
	if o == nil {
		return ""
	}
	return o.MetricName
}

func (o *BreakdownBeta) GetValue() float64 {
	if o == nil {
		return 0.0
	}
	return o.Value
}
