// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BreakdownBeta - The breakdown of a metric.
type BreakdownBeta struct {
	// The name of the metric.
	MetricName string `json:"metricName"`
	// Number of occurrences of the metric.
	Value float64 `json:"value"`
}
