// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteLabelAlphaInput - Deletes an existing label in the current Workspace.
type DeleteLabelAlphaInput struct {
}
