// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteInvitesV1Input - Removes pre-existing invitations to join a Workspace.
type DeleteInvitesV1Input struct {
}
