// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteTransformationBetaInput - The input of delete Transformation.
type DeleteTransformationBetaInput struct {
	// The Transformation id.
	TransformationID string `json:"transformationId"`
}

func (o *DeleteTransformationBetaInput) GetTransformationID() string {
	if o == nil {
		return ""
	}
	return o.TransformationID
}
