// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteDestinationV1Input - Deletes a single Destination by its id.
type DeleteDestinationV1Input struct {
}
