// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteUserGroupV1Input - Deletes a user group with a given group id from a Workspace.
type DeleteUserGroupV1Input struct {
}
