// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteLabelV1Input - Deletes an existing label in the current Workspace.
type DeleteLabelV1Input struct {
}
