// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteTransformationV1Input - The input of delete Transformation.
type DeleteTransformationV1Input struct {
}
