// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DisableEdgeFunctionsAlphaInput - Input for DisableEdgeFunctions.
type DisableEdgeFunctionsAlphaInput struct {
}
