// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EchoAlphaInput - EchoAlphaInput and EchoAlphaOutput are needed by unit tests in the generated Go code.
//
// If you change these, make sure `make clients` works locally, and generates the Go client correctly.
// Echo request with options.
type EchoAlphaInput struct {
}
