// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EventSourceV1 - Source represents a Segment Source.
type EventSourceV1 struct {
	// The id of the Source where the events came from.
	ID string `json:"id"`
	// The name of the Source, if applicable.
	Name *string `json:"name,omitempty"`
	// The slug of the Source, if applicable.
	Slug *string `json:"slug,omitempty"`
}

func (o *EventSourceV1) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *EventSourceV1) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *EventSourceV1) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}
