// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// FunctionV1ResourceType - The Function type.
//
// Config API note: equal to `type`.
type FunctionV1ResourceType string

const (
	FunctionV1ResourceTypeDestination       FunctionV1ResourceType = "DESTINATION"
	FunctionV1ResourceTypeInsertDestination FunctionV1ResourceType = "INSERT_DESTINATION"
	FunctionV1ResourceTypeSource            FunctionV1ResourceType = "SOURCE"
)

func (e FunctionV1ResourceType) ToPointer() *FunctionV1ResourceType {
	return &e
}

func (e *FunctionV1ResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DESTINATION":
		fallthrough
	case "INSERT_DESTINATION":
		fallthrough
	case "SOURCE":
		*e = FunctionV1ResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FunctionV1ResourceType: %v", v)
	}
}

// FunctionV1 - Represents a Function.
type FunctionV1 struct {
	// The max count of the batch for this Function.
	BatchMaxCount *float64 `json:"batchMaxCount,omitempty"`
	// The catalog id of this Function.
	CatalogID *string `json:"catalogId,omitempty"`
	// The Function code.
	Code *string `json:"code,omitempty"`
	// The time this Function was created.
	CreatedAt *string `json:"createdAt,omitempty"`
	// The id of the user who created this Function.
	CreatedBy *string `json:"createdBy,omitempty"`
	// The time of this Function's last deployment.
	DeployedAt *string `json:"deployedAt,omitempty"`
	// A description for this Function.
	Description *string `json:"description,omitempty"`
	// A display name for this Function.
	DisplayName *string `json:"displayName,omitempty"`
	// An identifier for this Function.
	ID *string `json:"id,omitempty"`
	// Whether the deployment of this Function is the latest version.
	IsLatestVersion *bool `json:"isLatestVersion,omitempty"`
	// The URL of the logo for this Function.
	LogoURL *string `json:"logoUrl,omitempty"`
	// The preview webhook URL for this Function.
	PreviewWebhookURL *string `json:"previewWebhookUrl,omitempty"`
	// The Function type.
	//
	// Config API note: equal to `type`.
	ResourceType *FunctionV1ResourceType `json:"resourceType,omitempty"`
	// The list of settings for this Function.
	Settings []FunctionSettingV1 `json:"settings,omitempty"`
}

func (o *FunctionV1) GetBatchMaxCount() *float64 {
	if o == nil {
		return nil
	}
	return o.BatchMaxCount
}

func (o *FunctionV1) GetCatalogID() *string {
	if o == nil {
		return nil
	}
	return o.CatalogID
}

func (o *FunctionV1) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *FunctionV1) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *FunctionV1) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *FunctionV1) GetDeployedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeployedAt
}

func (o *FunctionV1) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *FunctionV1) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *FunctionV1) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *FunctionV1) GetIsLatestVersion() *bool {
	if o == nil {
		return nil
	}
	return o.IsLatestVersion
}

func (o *FunctionV1) GetLogoURL() *string {
	if o == nil {
		return nil
	}
	return o.LogoURL
}

func (o *FunctionV1) GetPreviewWebhookURL() *string {
	if o == nil {
		return nil
	}
	return o.PreviewWebhookURL
}

func (o *FunctionV1) GetResourceType() *FunctionV1ResourceType {
	if o == nil {
		return nil
	}
	return o.ResourceType
}

func (o *FunctionV1) GetSettings() []FunctionSettingV1 {
	if o == nil {
		return nil
	}
	return o.Settings
}
