// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GenerateUploadURLForEdgeFunctionsAlphaInput - Input for GenerateSignedUrl.
type GenerateUploadURLForEdgeFunctionsAlphaInput struct {
}
