// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetConnectionStateFromWarehouseV1Input - Verifies the connection state of a Warehouse.
//
// Use this to check if a Warehouse is reachable, given its stored connection settings.
type GetConnectionStateFromWarehouseV1Input struct {
}
