// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetDestinationMetadataV1Input - Loads a Destination catalog item by id.
type GetDestinationMetadataV1Input struct {
}
