// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetDailyWorkspaceAPICallsUsageV1Input - Input to retrieve aggregated daily Workspace API calls in a billing period.
type GetDailyWorkspaceAPICallsUsageV1Input struct {
}
