// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetDailyPerSourceMTUUsageV1Input - Input to retrieve aggregated daily Source level MTU in a billing period.
type GetDailyPerSourceMTUUsageV1Input struct {
}
