// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetFilterInDestinationV1Input - Input for GetDestinationFilterV1.
type GetFilterInDestinationV1Input struct {
}
