// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetLatestFromEdgeFunctionsAlphaInput - Input for GetLatestFromEdgeFunctions.
type GetLatestFromEdgeFunctionsAlphaInput struct {
}
