// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetSourcesCatalogV1Input - Filter parameters used for loading the Sources public catalog.
type GetSourcesCatalogV1Input struct {
}
