// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetSubscriptionFromDestinationAlphaInput - Fetches a Destination subscription.
type GetSubscriptionFromDestinationAlphaInput struct {
}
