// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetTransformationBetaInput - The input of Transformation retrieval.
type GetTransformationBetaInput struct {
	// The Transformation id.
	TransformationID string `json:"transformationId"`
}

func (o *GetTransformationBetaInput) GetTransformationID() string {
	if o == nil {
		return ""
	}
	return o.TransformationID
}
