// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetWarehouseMetadataV1Input - Returns a Warehouse catalog item by id.
type GetWarehouseMetadataV1Input struct {
}
