// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetWarehousesCatalogV1Input - Filter parameters used for loading the Warehouses public catalog.
type GetWarehousesCatalogV1Input struct {
}
