// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// HandleWebhookInput - Function webhook input.
type HandleWebhookInput struct {
	// The webhook nonce.
	N string `json:"n"`
	// The webhook signature.
	S string `json:"s"`
	// The webhook timestamp.
	T string `json:"t"`
	// The Workspace id.
	W string `json:"w"`
}
