// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// HandleWebhookOutput - Function webhook output status.
type HandleWebhookOutput struct {
	// The http status code.
	StatusCode float64 `json:"statusCode"`
	// The status of the operation.
	Success bool `json:"success"`
}

func (o *HandleWebhookOutput) GetStatusCode() float64 {
	if o == nil {
		return 0.0
	}
	return o.StatusCode
}

func (o *HandleWebhookOutput) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}
