// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListFunctionsV1OutputPaginationOutput - Pagination metadata for a list response.
//
// Responses return this object alongside a list of resources, which provides the necessary metadata for manipulating a
// paginated collection. In operations that return lists, it's always present, though some of its fields might not be.
type ListFunctionsV1OutputPaginationOutput struct {
	// The current cursor within a collection.
	//
	// Consumers of the API must treat this value as opaque.
	Current string `json:"current"`
	// A pointer to the next page.
	//
	// This does not return when you retrieve the last page.
	//
	// Consumers of the API must treat this value as opaque.
	Next *string `json:"next,omitempty"`
	// A pointer to the previous page.
	//
	// This does not return when you retrieve the first page.
	//
	// Consumers of the API must treat this value as opaque.
	Previous *string `json:"previous,omitempty"`
	// The total number of entries available in the collection.
	//
	// If calculating it impacts performance, the response may omit this field.
	TotalEntries *float64 `json:"totalEntries,omitempty"`
}

func (o *ListFunctionsV1OutputPaginationOutput) GetCurrent() string {
	if o == nil {
		return ""
	}
	return o.Current
}

func (o *ListFunctionsV1OutputPaginationOutput) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ListFunctionsV1OutputPaginationOutput) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ListFunctionsV1OutputPaginationOutput) GetTotalEntries() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalEntries
}

// ListFunctionsV1Output - Lists Functions in a Workspace.
type ListFunctionsV1Output struct {
	// An array of Functions.
	Functions []ListFunctionItemV1 `json:"functions"`
	// Information about the pagination of this response.
	Pagination ListFunctionsV1OutputPaginationOutput `json:"pagination"`
}

func (o *ListFunctionsV1Output) GetFunctions() []ListFunctionItemV1 {
	if o == nil {
		return []ListFunctionItemV1{}
	}
	return o.Functions
}

func (o *ListFunctionsV1Output) GetPagination() ListFunctionsV1OutputPaginationOutput {
	if o == nil {
		return ListFunctionsV1OutputPaginationOutput{}
	}
	return o.Pagination
}
