// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListSourcesFromTrackingPlanV1Input - Lists all Sources associated with a Tracking Plan.
type ListSourcesFromTrackingPlanV1Input struct {
}
