// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListInsertFunctionInstancesAlphaInput - List all insert Function instances connected to the insert Function.
type ListInsertFunctionInstancesAlphaInput struct {
}
