// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListRolesV1Input - Returns a list of roles available to apply to permissions for users in the Workspace.
type ListRolesV1Input struct {
}
