// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListDeliveryMetricsSummaryFromDestinationBetaInput - Input to retrieve event delivery metrics summary for a Destination.
type ListDeliveryMetricsSummaryFromDestinationBetaInput struct {
}
