// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListLabelsAlphaInput - Retrieves all available labels for the current Workspace.
type ListLabelsAlphaInput struct {
}
