// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListDestinationsV1Input - Loads all Destinations connected to the current Workspace.
type ListDestinationsV1Input struct {
}
