// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListConnectedWarehousesFromSourceV1Input - Requests a list of Warehouses connected to a Source.
type ListConnectedWarehousesFromSourceV1Input struct {
}
