// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListAuditEventsV1OutputPaginationOutput - Pagination metadata for a list response.
//
// Responses return this object alongside a list of resources, which provides the necessary metadata for manipulating a
// paginated collection. In operations that return lists, it's always present, though some of its fields might not be.
type ListAuditEventsV1OutputPaginationOutput struct {
	// The current cursor within a collection.
	//
	// Consumers of the API must treat this value as opaque.
	Current string `json:"current"`
	// A pointer to the next page.
	//
	// This does not return when you retrieve the last page.
	//
	// Consumers of the API must treat this value as opaque.
	Next *string `json:"next,omitempty"`
	// A pointer to the previous page.
	//
	// This does not return when you retrieve the first page.
	//
	// Consumers of the API must treat this value as opaque.
	Previous *string `json:"previous,omitempty"`
	// The total number of entries available in the collection.
	//
	// If calculating it impacts performance, the response may omit this field.
	TotalEntries *float64 `json:"totalEntries,omitempty"`
}

func (o *ListAuditEventsV1OutputPaginationOutput) GetCurrent() string {
	if o == nil {
		return ""
	}
	return o.Current
}

func (o *ListAuditEventsV1OutputPaginationOutput) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ListAuditEventsV1OutputPaginationOutput) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ListAuditEventsV1OutputPaginationOutput) GetTotalEntries() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalEntries
}

// ListAuditEventsV1Output - Returns a list of Audit Trail events for the current Workspace.
type ListAuditEventsV1Output struct {
	// Audit trail events for the current Workspace.
	Events []AuditEventV1 `json:"events"`
	// Information about the pagination of this response.
	Pagination *ListAuditEventsV1OutputPaginationOutput `json:"pagination,omitempty"`
}

func (o *ListAuditEventsV1Output) GetEvents() []AuditEventV1 {
	if o == nil {
		return []AuditEventV1{}
	}
	return o.Events
}

func (o *ListAuditEventsV1Output) GetPagination() *ListAuditEventsV1OutputPaginationOutput {
	if o == nil {
		return nil
	}
	return o.Pagination
}
