// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListComputedTraitsAlphaInput - Input to list computed traits for a space id.
type ListComputedTraitsAlphaInput struct {
}
