// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListInvitesV1Input - Retrieves a list of existing invitations to join a Workspace.
type ListInvitesV1Input struct {
}
