// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListDeliveryMetricsSummaryFromDestinationBetaOutputDeliveryMetricsSummaryBeta - Defines the summary of delivery metrics for a Destination.
type ListDeliveryMetricsSummaryFromDestinationBetaOutputDeliveryMetricsSummaryBeta struct {
	// The Destination metadata id.
	DestinationMetadataID string `json:"destinationMetadataId"`
	// The summary of event delivery metrics for the requested Destination.
	Metrics []MetricBeta `json:"metrics"`
	// The Source id.
	//
	// Config API note: analogous to `parent`.
	SourceID string `json:"sourceId"`
}

// ListDeliveryMetricsSummaryFromDestinationBetaOutput - Output to retrieve event delivery metrics summary for a Destination.
type ListDeliveryMetricsSummaryFromDestinationBetaOutput struct {
	// The delivery metrics summary returned.
	DeliveryMetricsSummary ListDeliveryMetricsSummaryFromDestinationBetaOutputDeliveryMetricsSummaryBeta `json:"deliveryMetricsSummary"`
}
