// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListInvitesFromUserGroupV1Input - Looks up the invitees to a user group within a Workspace.
type ListInvitesFromUserGroupV1Input struct {
}
