// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListSyncsFromWarehouseAndSourceV1Input - Loads the most recent sync information for a Warehouse-source pair.
type ListSyncsFromWarehouseAndSourceV1Input struct {
}
