// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListProfilesWarehouseInSpaceAlphaInput - Gets all Profiles Warehouse based on spaceID and pagination.
type ListProfilesWarehouseInSpaceAlphaInput struct {
}
