// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListSelectiveSyncsFromWarehouseAndSourceV1Input - Get the Selective Sync configuration associated with a Warehouse.
type ListSelectiveSyncsFromWarehouseAndSourceV1Input struct {
}
