// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListRulesFromTrackingPlanV1Input - Lists a Tracking Plan's rules.
type ListRulesFromTrackingPlanV1Input struct {
}
