// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListConnectedSourcesFromWarehouseV1Input - Looks up the list of Sources connected to a Warehouse.
type ListConnectedSourcesFromWarehouseV1Input struct {
}
