// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListWorkspaceRegulationsV1Input - Input to list all Workspace-scoped regulations in a given Workspace.
type ListWorkspaceRegulationsV1Input struct {
}
