// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListUsersFromUserGroupV1Input - Looks up the members of a user group within a Workspace.
type ListUsersFromUserGroupV1Input struct {
}
