// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListSelectiveSyncsFromWarehouseAndSpaceAlphaInput - Get the Selective Sync configuration associated with a Space Warehouse Connection.
type ListSelectiveSyncsFromWarehouseAndSpaceAlphaInput struct {
}
