// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// LogosBeta - Represents a logo.
type LogosBeta struct {
	// The alternative text for this logo.
	Alt *string `json:"alt,omitempty"`
	// The default URL for this logo.
	Default string `json:"default"`
	// The logo mark.
	Mark *string `json:"mark,omitempty"`
}
