// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MetricBeta - The event delivery metric.
type MetricBeta struct {
	// Breakdown of metrics within a metric.
	Breakdown []BreakdownBeta `json:"breakdown,omitempty"`
	// The name of the metric.
	MetricName string `json:"metricName"`
	// Number of occurrences of the metric.
	Total float64 `json:"total"`
}
