// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MtuSnapshotV1 - A snapshot of MTU metrics within the given usage period.
type MtuSnapshotV1 struct {
	// A bigint of the number of anonymous users in this snapshot.
	Anonymous string `json:"anonymous"`
	// A bigint of the number of anonymous identified users in this snapshot.
	AnonymousIdentified string `json:"anonymousIdentified"`
	// A bigint of the number of identified users in this snapshot.
	Identified string `json:"identified"`
	// A bigint of the number of never identified users in this snapshot.
	NeverIdentified string `json:"neverIdentified"`
	// The end of the usage period, in unix time (seconds since epoch).
	PeriodEnd float64 `json:"periodEnd"`
	// The start of the usage period, in unix time (seconds since epoch).
	PeriodStart float64 `json:"periodStart"`
	// The timestamp of this snapshot within the billing cycle, in the ISO-8601 format.
	Timestamp string `json:"timestamp"`
}
