// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PropertyRenameBeta struct {
	// The new name to rename the property.
	NewName string `json:"newName"`
	// The old name of the property.
	OldName string `json:"oldName"`
}
