// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RemoveSourceConnectionFromWarehouseV1Input - Disconnects a Source from a Warehouse.
//
// Posting to this idempotent endpoint removes a connection between the Source and Warehouse, and blocks all syncing
// from the Source's collections into the chosen Warehouse Destination.
type RemoveSourceConnectionFromWarehouseV1Input struct {
}
