// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RemoveUsersFromUserGroupV1Input - Removes users or invites from a user group.
type RemoveUsersFromUserGroupV1Input struct {
}
