// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RemoveFilterFromDestinationV1Input - Input for DeleteDestinationFilterV1.
type RemoveFilterFromDestinationV1Input struct {
}
