// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ReplaceLabelsInSourceAlphaInput - Replaces all labels in a Source with a list of new labels.
type ReplaceLabelsInSourceAlphaInput struct {
	// The list of labels to replace in the Source.
	Labels []LabelAlpha `json:"labels"`
}

func (o *ReplaceLabelsInSourceAlphaInput) GetLabels() []LabelAlpha {
	if o == nil {
		return []LabelAlpha{}
	}
	return o.Labels
}
