// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SourceEventVolumeDatapointV1 - SourceEventVolumeDatapoint represents an individual timestamp/event count
// pair corresponding to a window of time designated by the granularity.
type SourceEventVolumeDatapointV1 struct {
	// The number of valid events Segment received in the given window,
	// after the events completed the validation process.
	Count float64 `json:"count"`
	// The timestamp that corresponds to the beginning of the window given
	// by the requested granularity.
	Time string `json:"time"`
}
