// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SourceAPICallSnapshotV1 - A snapshot of the number of API calls for a given Source in a Workspace.
type SourceAPICallSnapshotV1 struct {
	// A bigint of the number of API calls in this snapshot.
	APICalls string `json:"apiCalls"`
	// The Source id.
	SourceID string `json:"sourceId"`
	// Timestamp of this snapshot within the billing cycle in the ISO-8601 format.
	Timestamp string `json:"timestamp"`
}
