// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UsersPerSourceSnapshotV1 - A snapshot of MTU metrics for a given Source within the given usage period.
type UsersPerSourceSnapshotV1 struct {
	// A bigint of the number of anonymous users in this snapshot.
	Anonymous string `json:"anonymous"`
	// A bigint of the number of anonymous identified users in this snapshot.
	AnonymousIdentified string `json:"anonymousIdentified"`
	// A bigint of the number of identified users in this snapshot.
	Identified string `json:"identified"`
	// A bigint of the number of never identified users in this snapshot.
	NeverIdentified string `json:"neverIdentified"`
	// The end of the usage period, in unix time (seconds since epoch).
	PeriodEnd float64 `json:"periodEnd"`
	// The start of the usage period, in unix time (seconds since epoch).
	PeriodStart float64 `json:"periodStart"`
	// The Source id.
	SourceID string `json:"sourceId"`
	// The timestamp of this snapshot within the billing cycle, in the ISO-8601 format.
	Timestamp string `json:"timestamp"`
}

func (o *UsersPerSourceSnapshotV1) GetAnonymous() string {
	if o == nil {
		return ""
	}
	return o.Anonymous
}

func (o *UsersPerSourceSnapshotV1) GetAnonymousIdentified() string {
	if o == nil {
		return ""
	}
	return o.AnonymousIdentified
}

func (o *UsersPerSourceSnapshotV1) GetIdentified() string {
	if o == nil {
		return ""
	}
	return o.Identified
}

func (o *UsersPerSourceSnapshotV1) GetNeverIdentified() string {
	if o == nil {
		return ""
	}
	return o.NeverIdentified
}

func (o *UsersPerSourceSnapshotV1) GetPeriodEnd() float64 {
	if o == nil {
		return 0.0
	}
	return o.PeriodEnd
}

func (o *UsersPerSourceSnapshotV1) GetPeriodStart() float64 {
	if o == nil {
		return 0.0
	}
	return o.PeriodStart
}

func (o *UsersPerSourceSnapshotV1) GetSourceID() string {
	if o == nil {
		return ""
	}
	return o.SourceID
}

func (o *UsersPerSourceSnapshotV1) GetTimestamp() string {
	if o == nil {
		return ""
	}
	return o.Timestamp
}
