// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkspaceV1 - An organized group of Sources and Destinations managed by a team.
type WorkspaceV1 struct {
	// The unique identifier.
	ID string `json:"id"`
	// The human-readable name.
	Name string `json:"name"`
	// The URL-friendly slug.
	Slug string `json:"slug"`
}
