// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/operations"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/shared"
)

func (r *AddPermissionsToUserGroupV1InputResourceModel) ToCreateSDKType() *shared.AddPermissionsToUserGroupV1Input {
	var permissions []shared.PermissionInputV1 = nil
	for _, permissionsItem := range r.Permissions {
		var resources []shared.PermissionResourceV1 = nil
		for _, resourcesItem := range permissionsItem.Resources {
			id := resourcesItem.ID.ValueString()
			var labels []shared.AllowedLabelBeta = nil
			for _, labelsItem := range resourcesItem.Labels {
				description := new(string)
				if !labelsItem.Description.IsUnknown() && !labelsItem.Description.IsNull() {
					*description = labelsItem.Description.ValueString()
				} else {
					description = nil
				}
				key := labelsItem.Key.ValueString()
				value := labelsItem.Value.ValueString()
				labels = append(labels, shared.AllowedLabelBeta{
					Description: description,
					Key:         key,
					Value:       value,
				})
			}
			typeVar := shared.PermissionResourceV1Type(resourcesItem.Type.ValueString())
			resources = append(resources, shared.PermissionResourceV1{
				ID:     id,
				Labels: labels,
				Type:   typeVar,
			})
		}
		roleID := permissionsItem.RoleID.ValueString()
		permissions = append(permissions, shared.PermissionInputV1{
			Resources: resources,
			RoleID:    roleID,
		})
	}
	out := shared.AddPermissionsToUserGroupV1Input{
		Permissions: permissions,
	}
	return &out
}

func (r *AddPermissionsToUserGroupV1InputResourceModel) RefreshFromCreateResponse(resp *operations.AddPermissionsToUserGroupResponseBody) {
	if resp.Data == nil {
		r.Data = nil
	} else {
		r.Data = &AddPermissionsToUserGroupV1Output{}
		if len(r.Data.Permissions) > len(resp.Data.Permissions) {
			r.Data.Permissions = r.Data.Permissions[:len(resp.Data.Permissions)]
		}
		for permissionsCount, permissionsItem := range resp.Data.Permissions {
			var permissions1 AccessPermissionV1
			if len(permissions1.Resources) > len(permissionsItem.Resources) {
				permissions1.Resources = permissions1.Resources[:len(permissionsItem.Resources)]
			}
			for resourcesCount, resourcesItem := range permissionsItem.Resources {
				var resources1 PermissionResourceV1
				resources1.ID = types.StringValue(resourcesItem.ID)
				if len(resources1.Labels) > len(resourcesItem.Labels) {
					resources1.Labels = resources1.Labels[:len(resourcesItem.Labels)]
				}
				for labelsCount, labelsItem := range resourcesItem.Labels {
					var labels1 LabelV1
					if labelsItem.Description != nil {
						labels1.Description = types.StringValue(*labelsItem.Description)
					} else {
						labels1.Description = types.StringNull()
					}
					labels1.Key = types.StringValue(labelsItem.Key)
					labels1.Value = types.StringValue(labelsItem.Value)
					if labelsCount+1 > len(resources1.Labels) {
						resources1.Labels = append(resources1.Labels, labels1)
					} else {
						resources1.Labels[labelsCount].Description = labels1.Description
						resources1.Labels[labelsCount].Key = labels1.Key
						resources1.Labels[labelsCount].Value = labels1.Value
					}
				}
				resources1.Type = types.StringValue(string(resourcesItem.Type))
				if resourcesCount+1 > len(permissions1.Resources) {
					permissions1.Resources = append(permissions1.Resources, resources1)
				} else {
					permissions1.Resources[resourcesCount].ID = resources1.ID
					permissions1.Resources[resourcesCount].Labels = resources1.Labels
					permissions1.Resources[resourcesCount].Type = resources1.Type
				}
			}
			permissions1.RoleID = types.StringValue(permissionsItem.RoleID)
			permissions1.RoleName = types.StringValue(permissionsItem.RoleName)
			if permissionsCount+1 > len(r.Data.Permissions) {
				r.Data.Permissions = append(r.Data.Permissions, permissions1)
			} else {
				r.Data.Permissions[permissionsCount].Resources = permissions1.Resources
				r.Data.Permissions[permissionsCount].RoleID = permissions1.RoleID
				r.Data.Permissions[permissionsCount].RoleName = permissions1.RoleName
			}
		}
	}
}
