// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"segment/internal/sdk/pkg/models/operations"
	"segment/internal/sdk/pkg/models/shared"
)

func (r *AddSourceToTrackingPlanV1InputResourceModel) ToCreateSDKType() *shared.AddSourceToTrackingPlanV1Input {
	sourceID := r.SourceID.ValueString()
	out := shared.AddSourceToTrackingPlanV1Input{
		SourceID: sourceID,
	}
	return &out
}

func (r *AddSourceToTrackingPlanV1InputResourceModel) RefreshFromCreateResponse(resp *operations.AddSourceToTrackingPlanResponseBody) {
	if resp.Data == nil {
		r.Data = nil
	} else {
		r.Data = &AddSourceToTrackingPlanV1Output{}
		r.Data.Status = types.StringValue(string(resp.Data.Status))
	}
}
