// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/operations"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AddUsersToUserGroupV1InputResource{}
var _ resource.ResourceWithImportState = &AddUsersToUserGroupV1InputResource{}

func NewAddUsersToUserGroupV1InputResource() resource.Resource {
	return &AddUsersToUserGroupV1InputResource{}
}

// AddUsersToUserGroupV1InputResource defines the resource implementation.
type AddUsersToUserGroupV1InputResource struct {
	client *sdk.Segment
}

// AddUsersToUserGroupV1InputResourceModel describes the resource data model.
type AddUsersToUserGroupV1InputResourceModel struct {
	Data        *AddUsersToUserGroupV1Output `tfsdk:"data"`
	Emails      []types.String               `tfsdk:"emails"`
	UserGroupID types.String                 `tfsdk:"user_group_id"`
}

func (r *AddUsersToUserGroupV1InputResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_add_users_to_user_group_v1_input"
}

func (r *AddUsersToUserGroupV1InputResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "AddUsersToUserGroupV1Input Resource",

		Attributes: map[string]schema.Attribute{
			"data": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"user_group": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"id": schema.StringAttribute{
								Computed:    true,
								Description: `The id of the user group.`,
							},
							"member_count": schema.NumberAttribute{
								Computed:    true,
								Description: `The number of members in the user group.`,
							},
							"name": schema.StringAttribute{
								Computed:    true,
								Description: `The name of the user group.`,
							},
							"permissions": schema.ListNestedAttribute{
								Computed: true,
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"labels": schema.ListNestedAttribute{
											Computed: true,
											NestedObject: schema.NestedAttributeObject{
												Attributes: map[string]schema.Attribute{
													"description": schema.StringAttribute{
														Computed:    true,
														Description: `A description of what this label represents.`,
													},
													"key": schema.StringAttribute{
														Computed:    true,
														Description: `The key identifier for this label.`,
													},
													"value": schema.StringAttribute{
														Computed:    true,
														Description: `The value of this label.`,
													},
												},
											},
											Description: `The labels to attach to this permission.`,
										},
										"resources": schema.ListNestedAttribute{
											Computed: true,
											NestedObject: schema.NestedAttributeObject{
												Attributes: map[string]schema.Attribute{
													"id": schema.StringAttribute{
														Computed:    true,
														Description: `The id of this resource.`,
													},
													"labels": schema.ListNestedAttribute{
														Computed: true,
														NestedObject: schema.NestedAttributeObject{
															Attributes: map[string]schema.Attribute{
																"description": schema.StringAttribute{
																	Computed:    true,
																	Description: `A description of what this label represents.`,
																},
																"key": schema.StringAttribute{
																	Computed:    true,
																	Description: `The key identifier for this label.`,
																},
																"value": schema.StringAttribute{
																	Computed:    true,
																	Description: `The value of this label.`,
																},
															},
														},
														Description: `The labels that further refine access to this resource. Labels are exclusive to Workspace-level permissions.`,
													},
													"type": schema.StringAttribute{
														Computed: true,
														MarkdownDescription: `must be one of ["FUNCTION", "SOURCE", "SPACE", "WAREHOUSE", "WORKSPACE"]` + "\n" +
															`The type for this resource.`,
														Validators: []validator.String{
															stringvalidator.OneOf(
																"FUNCTION",
																"SOURCE",
																"SPACE",
																"WAREHOUSE",
																"WORKSPACE",
															),
														},
													},
												},
											},
											Description: `The resources associated with this permission.`,
										},
										"role_id": schema.StringAttribute{
											Computed:    true,
											Description: `The id of the role associated with this permission.`,
										},
										"role_name": schema.StringAttribute{
											Computed:    true,
											Description: `The name of the role associated with this permission.`,
										},
									},
								},
								Description: `The permissions associated with the user group.`,
							},
						},
						Description: `The updated the user group.`,
					},
				},
				Description: `Returns the updated user group.`,
			},
			"emails": schema.ListAttribute{
				PlanModifiers: []planmodifier.List{
					listplanmodifier.RequiresReplace(),
				},
				Required:    true,
				ElementType: types.StringType,
				Description: `The email addresses of the users and invites to add.`,
			},
			"user_group_id": schema.StringAttribute{
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Required: true,
			},
		},
	}
}

func (r *AddUsersToUserGroupV1InputResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Segment)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.Segment, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *AddUsersToUserGroupV1InputResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *AddUsersToUserGroupV1InputResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	addUsersToUserGroupV1Input := *data.ToCreateSDKType()
	userGroupID := data.UserGroupID.ValueString()
	request := operations.AddUsersToUserGroupRequest{
		AddUsersToUserGroupV1Input: addUsersToUserGroupV1Input,
		UserGroupID:                userGroupID,
	}
	res, err := r.client.IAMGroups.AddUsersToUserGroup(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.TwoHundredApplicationJSONObject == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromCreateResponse(res.TwoHundredApplicationJSONObject)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AddUsersToUserGroupV1InputResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *AddUsersToUserGroupV1InputResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Not Implemented; we rely entirely on CREATE API request response

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AddUsersToUserGroupV1InputResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *AddUsersToUserGroupV1InputResourceModel
	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	// Not Implemented; all attributes marked as RequiresReplace

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AddUsersToUserGroupV1InputResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *AddUsersToUserGroupV1InputResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Not Implemented; entity does not have a configured DELETE operation
}

func (r *AddUsersToUserGroupV1InputResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.AddError("Not Implemented", "No available import state operation is available for resource add_users_to_user_group_v1_input.")
}
