// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/operations"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/shared"
)

func (r *CreateTrackingPlanV1InputResourceModel) ToCreateSDKType() *shared.CreateTrackingPlanV1Input {
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	name := r.Name.ValueString()
	typeVar := shared.Type(r.Type.ValueString())
	out := shared.CreateTrackingPlanV1Input{
		Description: description,
		Name:        name,
		Type:        typeVar,
	}
	return &out
}

func (r *CreateTrackingPlanV1InputResourceModel) RefreshFromCreateResponse(resp *operations.CreateTrackingPlanResponseBody) {
	if resp.Data == nil {
		r.Data = nil
	} else {
		r.Data = &CreateTrackingPlanV1Output{}
		if resp.Data.TrackingPlan.CreatedAt != nil {
			r.Data.TrackingPlan.CreatedAt = types.StringValue(*resp.Data.TrackingPlan.CreatedAt)
		} else {
			r.Data.TrackingPlan.CreatedAt = types.StringNull()
		}
		if resp.Data.TrackingPlan.Description != nil {
			r.Data.TrackingPlan.Description = types.StringValue(*resp.Data.TrackingPlan.Description)
		} else {
			r.Data.TrackingPlan.Description = types.StringNull()
		}
		r.Data.TrackingPlan.ID = types.StringValue(resp.Data.TrackingPlan.ID)
		if resp.Data.TrackingPlan.Name != nil {
			r.Data.TrackingPlan.Name = types.StringValue(*resp.Data.TrackingPlan.Name)
		} else {
			r.Data.TrackingPlan.Name = types.StringNull()
		}
		if resp.Data.TrackingPlan.Slug != nil {
			r.Data.TrackingPlan.Slug = types.StringValue(*resp.Data.TrackingPlan.Slug)
		} else {
			r.Data.TrackingPlan.Slug = types.StringNull()
		}
		r.Data.TrackingPlan.Type = types.StringValue(string(resp.Data.TrackingPlan.Type))
		if resp.Data.TrackingPlan.UpdatedAt != nil {
			r.Data.TrackingPlan.UpdatedAt = types.StringValue(*resp.Data.TrackingPlan.UpdatedAt)
		} else {
			r.Data.TrackingPlan.UpdatedAt = types.StringNull()
		}
	}
}
