// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/operations"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/shared"
)

func (r *CreateTrackingPlanV1InputResourceModel) ToSharedCreateTrackingPlanV1Input() *shared.CreateTrackingPlanV1Input {
	description := new(string)
	if !r.Description.IsUnknown() && !r.Description.IsNull() {
		*description = r.Description.ValueString()
	} else {
		description = nil
	}
	name := r.Name.ValueString()
	typeVar := shared.Type(r.Type.ValueString())
	out := shared.CreateTrackingPlanV1Input{
		Description: description,
		Name:        name,
		Type:        typeVar,
	}
	return &out
}

func (r *CreateTrackingPlanV1InputResourceModel) RefreshFromOperationsCreateTrackingPlanResponseBody(resp *operations.CreateTrackingPlanResponseBody) {
	if resp != nil {
		if resp.Data == nil {
			r.Data = nil
		} else {
			r.Data = &CreateTrackingPlanV1Output{}
			r.Data.TrackingPlan.CreatedAt = types.StringPointerValue(resp.Data.TrackingPlan.CreatedAt)
			r.Data.TrackingPlan.Description = types.StringPointerValue(resp.Data.TrackingPlan.Description)
			r.Data.TrackingPlan.ID = types.StringValue(resp.Data.TrackingPlan.ID)
			r.Data.TrackingPlan.Name = types.StringPointerValue(resp.Data.TrackingPlan.Name)
			r.Data.TrackingPlan.Slug = types.StringPointerValue(resp.Data.TrackingPlan.Slug)
			r.Data.TrackingPlan.Type = types.StringValue(string(resp.Data.TrackingPlan.Type))
			r.Data.TrackingPlan.UpdatedAt = types.StringPointerValue(resp.Data.TrackingPlan.UpdatedAt)
		}
	}
}
