// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"encoding/json"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"math/big"
	"segment/internal/sdk/pkg/models/shared"
)

func (r *CreateInvitesV1InputResourceModel) ToCreateSDKType() *shared.CreateInvitesV1Input {
	var invites []shared.InviteV1 = nil
	for _, invitesItem := range r.Invites {
		email := invitesItem.Email.ValueString()
		var permissions []shared.InvitePermissionV1 = nil
		for _, permissionsItem := range invitesItem.Permissions {
			var labels []shared.AllowedLabelBeta = nil
			for _, labelsItem := range permissionsItem.Labels {
				description := new(string)
				if !labelsItem.Description.IsUnknown() && !labelsItem.Description.IsNull() {
					*description = labelsItem.Description.ValueString()
				} else {
					description = nil
				}
				key := labelsItem.Key.ValueString()
				value := labelsItem.Value.ValueString()
				labels = append(labels, shared.AllowedLabelBeta{
					Description: description,
					Key:         key,
					Value:       value,
				})
			}
			var resources []shared.ResourceV1 = nil
			for _, resourcesItem := range permissionsItem.Resources {
				id := resourcesItem.ID.ValueString()
				typeVar := shared.ResourceV1Type(resourcesItem.Type.ValueString())
				resources = append(resources, shared.ResourceV1{
					ID:   id,
					Type: typeVar,
				})
			}
			roleID := permissionsItem.RoleID.ValueString()
			permissions = append(permissions, shared.InvitePermissionV1{
				Labels:    labels,
				Resources: resources,
				RoleID:    roleID,
			})
		}
		invites = append(invites, shared.InviteV1{
			Email:       email,
			Permissions: permissions,
		})
	}
	out := shared.CreateInvitesV1Input{
		Invites: invites,
	}
	return &out
}

func (r *CreateInvitesV1InputResourceModel) RefreshFromCreateResponse(resp *shared.RequestErrorEnvelope) {
	r.Errors = nil
	for _, errorsItem := range resp.Errors {
		var errors1 RequestError
		if errorsItem.Data == nil {
			errors1.Data = types.StringNull()
		} else {
			dataResult, _ := json.Marshal(errorsItem.Data)
			errors1.Data = types.StringValue(string(dataResult))
		}
		if errorsItem.Field != nil {
			errors1.Field = types.StringValue(*errorsItem.Field)
		} else {
			errors1.Field = types.StringNull()
		}
		if errorsItem.Message != nil {
			errors1.Message = types.StringValue(*errorsItem.Message)
		} else {
			errors1.Message = types.StringNull()
		}
		if errorsItem.Status != nil {
			errors1.Status = types.NumberValue(big.NewFloat(float64(*errorsItem.Status)))
		} else {
			errors1.Status = types.NumberNull()
		}
		errors1.Type = types.StringValue(errorsItem.Type)
		r.Errors = append(r.Errors, errors1)
	}
}
