// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"encoding/json"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/operations"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/shared"
)

func (r *CreateSourceV1InputResourceModel) ToCreateSDKType() *shared.CreateSourceV1Input {
	enabled := r.Enabled.ValueBool()
	metadataID := r.MetadataID.ValueString()
	settings := make(map[string]interface{})
	for settingsKey, settingsValue := range r.Settings {
		var settingsInst interface{}
		_ = json.Unmarshal([]byte(settingsValue.ValueString()), &settingsInst)
		settings[settingsKey] = settingsInst
	}
	slug := r.Slug.ValueString()
	out := shared.CreateSourceV1Input{
		Enabled:    enabled,
		MetadataID: metadataID,
		Settings:   settings,
		Slug:       slug,
	}
	return &out
}

func (r *CreateSourceV1InputResourceModel) RefreshFromCreateResponse(resp *operations.CreateSourceResponseBody) {
	if resp.Data == nil {
		r.Data = nil
	} else {
		r.Data = &CreateSourceV1Output{}
		r.Data.Source.Enabled = types.BoolValue(resp.Data.Source.Enabled)
		r.Data.Source.ID = types.StringValue(resp.Data.Source.ID)
		r.Data.Source.Labels = nil
		for _, labelsItem := range resp.Data.Source.Labels {
			var labels1 LabelV1
			if labelsItem.Description != nil {
				labels1.Description = types.StringValue(*labelsItem.Description)
			} else {
				labels1.Description = types.StringNull()
			}
			labels1.Key = types.StringValue(labelsItem.Key)
			labels1.Value = types.StringValue(labelsItem.Value)
			r.Data.Source.Labels = append(r.Data.Source.Labels, labels1)
		}
		r.Data.Source.Metadata.Categories = nil
		for _, v := range resp.Data.Source.Metadata.Categories {
			r.Data.Source.Metadata.Categories = append(r.Data.Source.Metadata.Categories, types.StringValue(v))
		}
		r.Data.Source.Metadata.Description = types.StringValue(resp.Data.Source.Metadata.Description)
		r.Data.Source.Metadata.ID = types.StringValue(resp.Data.Source.Metadata.ID)
		r.Data.Source.Metadata.IsCloudEventSource = types.BoolValue(resp.Data.Source.Metadata.IsCloudEventSource)
		if resp.Data.Source.Metadata.Logos.Alt != nil {
			r.Data.Source.Metadata.Logos.Alt = types.StringValue(*resp.Data.Source.Metadata.Logos.Alt)
		} else {
			r.Data.Source.Metadata.Logos.Alt = types.StringNull()
		}
		r.Data.Source.Metadata.Logos.Default = types.StringValue(resp.Data.Source.Metadata.Logos.Default)
		if resp.Data.Source.Metadata.Logos.Mark != nil {
			r.Data.Source.Metadata.Logos.Mark = types.StringValue(*resp.Data.Source.Metadata.Logos.Mark)
		} else {
			r.Data.Source.Metadata.Logos.Mark = types.StringNull()
		}
		r.Data.Source.Metadata.Name = types.StringValue(resp.Data.Source.Metadata.Name)
		r.Data.Source.Metadata.Options = nil
		for _, optionsItem := range resp.Data.Source.Metadata.Options {
			var options1 IntegrationOptionBeta
			if optionsItem.DefaultValue == nil {
				options1.DefaultValue = types.StringNull()
			} else {
				defaultValueResult, _ := json.Marshal(optionsItem.DefaultValue)
				options1.DefaultValue = types.StringValue(string(defaultValueResult))
			}
			if optionsItem.Description != nil {
				options1.Description = types.StringValue(*optionsItem.Description)
			} else {
				options1.Description = types.StringNull()
			}
			if optionsItem.Label != nil {
				options1.Label = types.StringValue(*optionsItem.Label)
			} else {
				options1.Label = types.StringNull()
			}
			options1.Name = types.StringValue(optionsItem.Name)
			options1.Required = types.BoolValue(optionsItem.Required)
			options1.Type = types.StringValue(optionsItem.Type)
			r.Data.Source.Metadata.Options = append(r.Data.Source.Metadata.Options, options1)
		}
		r.Data.Source.Metadata.Slug = types.StringValue(resp.Data.Source.Metadata.Slug)
		if resp.Data.Source.Name != nil {
			r.Data.Source.Name = types.StringValue(*resp.Data.Source.Name)
		} else {
			r.Data.Source.Name = types.StringNull()
		}
		if r.Data.Source.Settings == nil && len(resp.Data.Source.Settings) > 0 {
			r.Data.Source.Settings = make(map[string]types.String)
			for key1, value1 := range resp.Data.Source.Settings {
				result, _ := json.Marshal(value1)
				r.Data.Source.Settings[key1] = types.StringValue(string(result))
			}
		}
		r.Data.Source.Slug = types.StringValue(resp.Data.Source.Slug)
		r.Data.Source.WorkspaceID = types.StringValue(resp.Data.Source.WorkspaceID)
		r.Data.Source.WriteKeys = nil
		for _, v := range resp.Data.Source.WriteKeys {
			r.Data.Source.WriteKeys = append(r.Data.Source.WriteKeys, types.StringValue(v))
		}
	}
}
