// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"segment/internal/sdk/pkg/models/shared"
)

func (r *CreateFunctionDeploymentV1OutputResourceModel) RefreshFromCreateResponse(resp *shared.CreateFunctionDeploymentV1Output) {
	r.FunctionDeployment.Status = types.StringValue(string(resp.FunctionDeployment.Status))
}
