// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk"
	"github.com/scentregroup/terraform-provider-segment/internal/sdk/pkg/models/shared"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ provider.Provider = &SegmentProvider{}

type SegmentProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// SegmentProviderModel describes the provider data model.
type SegmentProviderModel struct {
	ServerURL types.String `tfsdk:"server_url"`
	Token     types.String `tfsdk:"token"`
}

func (p *SegmentProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "segment"
	resp.Version = p.version
}

func (p *SegmentProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: `Segment Public API: The Segment Public API helps you manage your Segment Workspaces and its resources. You can use the API to perform CRUD (create, read, update, delete) operations at no extra charge. This includes working with resources such as Sources, Destinations, Warehouses, Tracking Plans, and the Segment Destinations and Sources Catalogs.` + "\n" +
			`` + "\n" +
			`All CRUD endpoints in the API follow REST conventions and use standard HTTP methods. Different URL endpoints represent different resources in a Workspace.` + "\n" +
			`` + "\n" +
			`See the next sections for more information on how to use the Segment Public API.` + "\n" +
			``,
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				MarkdownDescription: "Server URL (defaults to https://api.segmentapis.com)",
				Optional:            true,
				Required:            false,
			},
			"token": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
			},
		},
	}
}

func (p *SegmentProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data SegmentProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	ServerURL := data.ServerURL.ValueString()

	if ServerURL == "" {
		ServerURL = "https://api.segmentapis.com"
	}

	token := data.Token.ValueString()
	security := shared.Security{
		Token: token,
	}

	opts := []sdk.SDKOption{
		sdk.WithServerURL(ServerURL),
		sdk.WithSecurity(security),
	}
	client := sdk.New(opts...)

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *SegmentProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewAddConnectionFromSourceToWarehouseV1OutputResource,
		NewAddLabelsToSourceV1InputResource,
		NewAddPermissionsToUserGroupV1InputResource,
		NewAddPermissionsToUserV1InputResource,
		NewAddSourceToTrackingPlanV1InputResource,
		NewAddUsersToUserGroupV1InputResource,
		NewCreateCloudSourceRegulationV1InputResource,
		NewCreateDestinationV1InputResource,
		NewCreateFilterForDestinationV1InputResource,
		NewCreateFunctionDeploymentV1OutputResource,
		NewCreateFunctionV1InputResource,
		NewCreateInvitesV1InputResource,
		NewCreateLabelV1InputResource,
		NewCreateSourceRegulationV1InputResource,
		NewCreateSourceV1InputResource,
		NewCreateTrackingPlanV1InputResource,
		NewCreateTransformationV1InputResource,
		NewCreateUserGroupV1InputResource,
		NewCreateValidationInWarehouseV1InputResource,
		NewCreateWarehouseV1InputResource,
		NewCreateWorkspaceRegulationV1InputResource,
		NewPreviewDestinationFilterV1InputResource,
	}
}

func (p *SegmentProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &SegmentProvider{
			version: version,
		}
	}
}
