// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type AddUsersToUserGroupV1Output struct {
	UserGroup AddUsersToUserGroupV1OutputUserGroupV1 `tfsdk:"user_group"`
}
