// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateWarehouseV1OutputWarehouseV1 struct {
	Enabled     types.Bool                                 `tfsdk:"enabled"`
	ID          types.String                               `tfsdk:"id"`
	Metadata    CreateWarehouseV1OutputWarehouseMetadataV1 `tfsdk:"metadata"`
	Settings    map[string]types.String                    `tfsdk:"settings"`
	WorkspaceID types.String                               `tfsdk:"workspace_id"`
}
