// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateDestinationV1OutputDestinationMetadataPlatformsV1 struct {
	Browser types.Bool `tfsdk:"browser"`
	Mobile  types.Bool `tfsdk:"mobile"`
	Server  types.Bool `tfsdk:"server"`
}
