// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type FQLDefinedPropertyV1 struct {
	Fql          types.String `tfsdk:"fql"`
	PropertyName types.String `tfsdk:"property_name"`
}
