// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateSourceV1OutputSourceV1 struct {
	Enabled     types.Bool                           `tfsdk:"enabled"`
	ID          types.String                         `tfsdk:"id"`
	Labels      []LabelV1                            `tfsdk:"labels"`
	Metadata    CreateSourceV1OutputSourceMetadataV1 `tfsdk:"metadata"`
	Name        types.String                         `tfsdk:"name"`
	Settings    map[string]types.String              `tfsdk:"settings"`
	Slug        types.String                         `tfsdk:"slug"`
	WorkspaceID types.String                         `tfsdk:"workspace_id"`
	WriteKeys   []types.String                       `tfsdk:"write_keys"`
}
