// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type DestinationFilterActionV1 struct {
	Fields  map[string]types.String `tfsdk:"fields"`
	Path    types.String            `tfsdk:"path"`
	Percent types.Number            `tfsdk:"percent"`
	Type    types.String            `tfsdk:"type"`
}
