// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateInvitesV1Output struct {
	Emails []types.String `tfsdk:"emails"`
}
