// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type UserGroup struct {
	ID          types.String   `tfsdk:"id"`
	MemberCount types.Number   `tfsdk:"member_count"`
	Name        types.String   `tfsdk:"name"`
	Permissions []PermissionV1 `tfsdk:"permissions"`
}
