// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type DestinationMetadataActionFieldV1 struct {
	AllowNull    types.Bool   `tfsdk:"allow_null"`
	Choices      types.String `tfsdk:"choices"`
	DefaultValue types.String `tfsdk:"default_value"`
	Description  types.String `tfsdk:"description"`
	Dynamic      types.Bool   `tfsdk:"dynamic"`
	FieldKey     types.String `tfsdk:"field_key"`
	ID           types.String `tfsdk:"id"`
	Label        types.String `tfsdk:"label"`
	Multiple     types.Bool   `tfsdk:"multiple"`
	Placeholder  types.String `tfsdk:"placeholder"`
	Required     types.Bool   `tfsdk:"required"`
	SortOrder    types.Number `tfsdk:"sort_order"`
	Type         types.String `tfsdk:"type"`
}
