// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type CreateFilterForDestinationV1Output struct {
	Filter CreateFilterForDestinationV1OutputDestinationFilterV1 `tfsdk:"filter"`
}
