// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type PreviewDestinationFilterV1InputFilter struct {
	Actions []DestinationFilterActionV1 `tfsdk:"actions"`
	If      types.String                `tfsdk:"if"`
}
