// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type AccessPermissionV1 struct {
	Resources []PermissionResourceV1 `tfsdk:"resources"`
	RoleID    types.String           `tfsdk:"role_id"`
	RoleName  types.String           `tfsdk:"role_name"`
}
