// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateValidationInWarehouseV1Output struct {
	Status types.String `tfsdk:"status"`
}
