// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Destination struct {
	Enabled  types.Bool                        `tfsdk:"enabled"`
	ID       types.String                      `tfsdk:"id"`
	Metadata CreateDestinationV1OutputMetadata `tfsdk:"metadata"`
	Name     types.String                      `tfsdk:"name"`
	Settings map[string]types.String           `tfsdk:"settings"`
	SourceID types.String                      `tfsdk:"source_id"`
}
