// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type DestinationMetadataComponentV1 struct {
	Code  types.String `tfsdk:"code"`
	Owner types.String `tfsdk:"owner"`
	Type  types.String `tfsdk:"type"`
}
