// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Filter struct {
	Actions       []DestinationFilterActionV1 `tfsdk:"actions"`
	CreatedAt     types.String                `tfsdk:"created_at"`
	Description   types.String                `tfsdk:"description"`
	DestinationID types.String                `tfsdk:"destination_id"`
	Enabled       types.Bool                  `tfsdk:"enabled"`
	ID            types.String                `tfsdk:"id"`
	If            types.String                `tfsdk:"if"`
	SourceID      types.String                `tfsdk:"source_id"`
	Title         types.String                `tfsdk:"title"`
	UpdatedAt     types.String                `tfsdk:"updated_at"`
}
