// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type PermissionResourceV1 struct {
	ID     types.String `tfsdk:"id"`
	Labels []LabelV1    `tfsdk:"labels"`
	Type   types.String `tfsdk:"type"`
}
