// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type PreviewDestinationFilterV1Output struct {
	InputPayload map[string]types.String `tfsdk:"input_payload"`
	Result       *Result                 `tfsdk:"result"`
}
