// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Warehouse struct {
	Enabled     types.Bool                      `tfsdk:"enabled"`
	ID          types.String                    `tfsdk:"id"`
	Metadata    CreateWarehouseV1OutputMetadata `tfsdk:"metadata"`
	Settings    map[string]types.String         `tfsdk:"settings"`
	WorkspaceID types.String                    `tfsdk:"workspace_id"`
}
